Repository Kernel360/f1-Orury-Client, pull requests merged in 2023-12, with the labels that each got.

#2 [CHORE] #1 프로젝트 세팅
  .eslintrc.json
  .gitignore
  .prettierrc.cjs
  next.config.js
  package.json
  postcss.config.js
  prettier.config.js
  src/app/favicon.ico
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  tailwind.config.ts
  tsconfig.json
Labels: 📱 FE, ⚙️Settings

#6 Design: #5 홈 UI 작업
  assets/fonts/Giants-Regular.ttf
  assets/icons/community.svg
  assets/icons/crew.svg
  assets/icons/home.svg
  assets/icons/index.js
  assets/icons/map.svg
  assets/icons/my.svg
  package-lock.json
  package.json
  public/board.svg
  public/crew.svg
  public/favicon.ico
  public/index.js
  public/kakao.svg
  public/kakao.webp
  public/map.svg
  src/app/custom.d.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/app/signin/layout.tsx
  src/app/signin/page.tsx
  src/app/styles/globals.css
  src/app/ui/NavigateBlock.tsx
  src/app/ui/common/Title.tsx
  src/app/ui/fonts.ts
  src/constants/ui/navigateBlock.js
  src/types/ui/navigateBlock.ts
  tailwind.config.ts
Labels: 📱 FE, 🎨 Html&css

#10 Fix: #9 svg file import path error
  package-lock.json
  package.json
  src/app/page.tsx
  src/app/ui/NavigateBlock.tsx
  src/app/ui/buttons/Kakao.tsx
  src/app/ui/common/Navbar.tsx
  src/constants/ui/navigateBlock.js
  tsconfig.json
Labels: 🐞 Fix, 📱 FE

#12 Chore: #11 husky, lint-staged 설치
  .eslintignore
  .eslintrc.json
  .husky/pre-commit
  package-lock.json
  package.json
  public/index.js
  src/app/page.tsx
  src/app/ui/NavigateBlock.tsx
  src/app/ui/buttons/Kakao.tsx
  src/app/ui/common/Navbar.tsx
  src/constants/ui/navigateBlock.js
  tailwind.config.ts
  tsconfig.json
Labels: 🐞 Fix, 📱 FE, ⚙️Settings

#14 Design: #13 공지사항 블럭 UI 작업
  assets/icons/active/crew-active.svg
  assets/icons/active/home-active.svg
  assets/icons/active/map-active.svg
  assets/icons/active/my-active.svg
  assets/icons/announce.svg
  assets/icons/bar.svg
  assets/icons/home.svg
  assets/icons/index.js
  assets/icons/my.svg
  assets/icons/navbar/active/community-active.svg
  assets/icons/navbar/active/crew-active.svg
  assets/icons/navbar/active/home-active.svg
  assets/icons/navbar/active/map-active.svg
  assets/icons/navbar/active/my-active.svg
  assets/icons/navbar/community.svg
  assets/icons/navbar/crew.svg
  assets/icons/navbar/home.svg
  assets/icons/navbar/map.svg
  assets/icons/navbar/my.svg
  src/app/_components/home/Announcement.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/ui/NavigateBlock.tsx
  src/app/ui/common/Navbar.tsx
  src/app/ui/common/Title.tsx
  tailwind.config.ts
Labels: 📱 FE, 🎨 Html&css

#20 Design: #19 Search Bar UI 작업
  README.md
  assets/icons/index.js
  assets/icons/notice.svg
  assets/icons/searchBar/index.js
  assets/icons/searchBar/magnifying-glass.svg
  assets/icons/searchBar/x-circle.svg
  db.json
  src/app/(domain)/community/layout.tsx
  src/app/_components/community/SearchBar.tsx
  src/app/_components/home/Notice.tsx
  src/app/page.tsx
Labels: 📱 FE, 🎨 Html&css

#22 Settings: 소셜 로그인 프론트단 세팅
  package-lock.json
  package.json
  src/app/(domain)/community/api/getPosts.ts
  src/app/_components/ui/buttons/Kakao.tsx
  src/app/_components/ui/buttons/signout.tsx
  src/app/api/auth/[...nextauth].ts
  src/app/api/auth/[...nextauth]/route.ts
  src/app/my-page/page.tsx
  src/app/signin/page.tsx
  src/middleware.ts
  src/types/next-auth.d.ts
Labels: 📱 FE, ⚙️Settings

#26 Design: #25 comment input
  assets/icons/community/commentBar/send.svg
  assets/icons/community/searchBar/index.js
  assets/icons/community/searchBar/magnifying-glass.svg
  assets/icons/community/searchBar/x-circle.svg
  src/app/(domain)/community/[id]/page.tsx
  src/app/(domain)/community/layout.tsx
  src/app/_components/community/CommentBar.tsx
  src/app/_components/community/SearchBar.tsx
  src/app/_components/ui/common/Header.tsx
Labels: 📱 FE, 🎨 Html&css

#28 Design: #27 게시판 댓글 UI 작업
  assets/icons/community/index.js
  assets/icons/community/reply.svg
  assets/icons/user/comment.svg
  assets/icons/user/ellipsis.svg
  assets/icons/user/index.js
  assets/icons/user/thumbs-up.svg
  src/app/(domain)/community/[id]/api/postDetail.d.ts
  src/app/(domain)/community/[id]/page.tsx
  src/app/(domain)/community/page.tsx
  src/app/_components/community/Comment.tsx
  src/app/_components/community/Counts.tsx
  src/app/_components/community/User.tsx
  src/app/_components/community/comment/Comment.tsx
  src/app/_components/community/comment/CommentBar.tsx
  src/app/_components/community/comment/CommentButtons.tsx
  src/lib/comment.json
  src/types/community/comment.ts
  src/types/community/commentButtons.ts
  src/types/community/user.ts
  src/types/response.d.ts
Labels: 📱 FE, 🎨 Html&css

#30 Design: #29 마이페이지 UI 구현
  .eslintrc.json
  assets/icons/my-page/camera.svg
  assets/icons/my-page/default-Profile-Image.svg
  assets/icons/my-page/index.js
  assets/icons/my-page/pencil.svg
  assets/icons/my-page/right.svg
  next.config.js
  src/app/(domain)/community/[id]/api/postDetail.d.ts
  src/app/_components/my-page/Activity.tsx
  src/app/_components/my-page/Heading.tsx
  src/app/_components/my-page/Profile.tsx
  src/app/_components/my-page/Withdrawal.tsx
  src/app/_components/my-page/index.js
  src/app/_components/my-page/privacy/Content.tsx
  src/app/_components/my-page/privacy/Privacy.tsx
  src/app/_components/ui/buttons/Button.tsx
  src/app/_components/ui/buttons/signout.tsx
  src/app/my-page/api/getMypage.d.ts
  src/app/my-page/page.tsx
  src/constants/my-page/activity.js
  src/constants/my-page/privacy.js
  src/constants/ui/common/header.js
  src/lib/mypage.json
  src/middleware.ts
  src/types/my-page/privacy.ts
Labels: 📱 FE, 🎨 Html&css

#32 Design: #31 공통 모달 UI 구현
  assets/icons/community/active/thumbs-up-active.svg
  assets/icons/community/thumbs-up.svg
  assets/icons/modal/index.js
  assets/icons/modal/warning.svg
  src/app/_components/community/User.tsx
  src/app/_components/community/comment/CommentBar.tsx
  src/app/_components/my-page/Withdrawal.tsx
  src/app/_components/ui/common/Header.tsx
  src/app/_components/ui/common/Modal.tsx
  src/app/_components/ui/common/Navbar.tsx
  src/app/my-page/page.tsx
  src/app/styles/globals.css
  src/constants/my-page/withdrawal.js
  tailwind.config.ts
Labels: ✨ Feature, 📱 FE, 🎨 Html&css

#34 Design: #33 회원가입 온보딩 페이지 UI 작업
  .eslintrc.json
  assets/icons/signup/checked.svg
  assets/icons/signup/index.js
  assets/icons/signup/unchecked.svg
  jest.config.ts
  jest.setup.js
  package-lock.json
  package.json
  src/app/_components/signup/Banner.tsx
  src/app/_components/signup/BirthInput.tsx
  src/app/_components/signup/Check.tsx
  src/app/_components/signup/Gender.tsx
  src/app/_components/signup/InvalidMessage.tsx
  src/app/_components/ui/buttons/Button.tsx
  src/app/my-page/page.tsx
  src/app/signup/page.tsx
  src/constants/signup/index.js
  src/store/signup/signupStore.ts
  src/types/signup/index.ts
  src/validator/index.js
  src/validator/is-valid-birth/index.js
  src/validator/is-valid-birth/index.test.js
  tailwind.config.ts
  tsconfig.json
Labels: 📱 FE, 🎨 Html&css, ✅ Test

#36 Feat: #35 글 작성 및 관련 Floating button 기능 구현
  assets/icons/community/index.js
  assets/icons/community/write.svg
  assets/icons/write/add.svg
  assets/icons/write/camera.svg
  assets/icons/write/index.js
  src/app/(domain)/community/page.tsx
  src/app/_components/my-page/Profile.tsx
  src/app/_components/ui/buttons/Floating.tsx
  src/app/_components/ui/common/Header.tsx
  src/app/_components/ui/common/Input.tsx
  src/app/_components/ui/common/Textarea.tsx
  src/app/_components/write/PhotoBooth.tsx
  src/app/layout.tsx
  src/app/styles/globals.css
  src/app/write/page.tsx
  src/types/ui/common/input.ts
  src/types/ui/common/textarea.ts
Labels: ✨ Feature, 📱 FE, 🎨 Html&css

#39 Feat: MSW를 추가한다.
  .eslintrc.json
  .gitignore
  db.json
  env.d.ts
  package-lock.json
  package.json
  src/__mock__/browser.ts
  src/__mock__/data/comment.mock.ts
  src/__mock__/data/mypage.mock.ts
  src/__mock__/data/post.mock.ts
  src/__mock__/data/profile.mock.ts
  src/__mock__/handler/server/community.ts
  src/__mock__/handler/server/crew.ts
  src/__mock__/handler/server/index.ts
  src/__mock__/handler/server/map.ts
  src/app/(domain)/community/[id]/api/getDetail.ts
  src/app/(domain)/community/[id]/page.tsx
  src/app/(domain)/community/api/getPosts.ts
  src/app/_components/ui/buttons/SignOut.tsx
  src/app/layout.tsx
  src/app/my-page/page.tsx
  src/constants/api/end-point.ts
  src/constants/api/index.ts
  src/lib/axios/axios-instance.ts
  src/lib/comment.json
  src/lib/mypage.json
Labels: ✨ Feature, 🔨 Refactor, 📱 FE, ⚙️Settings

#41 Chore: react-hook-form & zod 설치 및 회원가입 폼 리팩토링 진행
  package-lock.json
  package.json
  src/app/(domain)/community/[id]/page.tsx
  src/app/(domain)/community/_components/CountItem.tsx
  src/app/(domain)/community/_components/Counts.tsx
  src/app/(domain)/community/_components/Post.tsx
  src/app/(domain)/community/_components/SearchBar.tsx
  src/app/(domain)/community/_components/Tabs.tsx
  src/app/(domain)/community/_components/User.tsx
  src/app/(domain)/community/_components/comment/Comment.tsx
  src/app/(domain)/community/_components/comment/CommentBar.tsx
  src/app/(domain)/community/_components/comment/CommentButtons.tsx
  src/app/(domain)/community/layout.tsx
  src/app/(domain)/community/page.tsx
  src/app/(domain)/layout.tsx
  src/app/_components/Notice.tsx
  src/app/_components/signup/BirthInput.tsx
  src/app/_components/signup/Gender.tsx
  src/app/layout.tsx
  src/app/my-page/_components/Activity.tsx
  src/app/my-page/_components/Heading.tsx
  src/app/my-page/_components/Profile.tsx
  src/app/my-page/_components/Withdrawal.tsx
  src/app/my-page/_components/index.js
  src/app/my-page/_components/privacy/Content.tsx
  src/app/my-page/_components/privacy/Privacy.tsx
  src/app/my-page/layout.tsx
  src/app/my-page/page.tsx
  src/app/page.tsx
  src/app/signin/page.tsx
  src/app/signup/_components/Banner.tsx
  src/app/signup/_components/Check.tsx
  src/app/signup/_components/InvalidMessage.tsx
  src/app/signup/_components/SignUpForm.tsx
  src/app/signup/page.tsx
  src/app/signup/schema.ts
  src/app/ui/NavigateBlock.tsx
  src/app/ui/buttons/Button.tsx
  src/app/ui/buttons/Floating.tsx
  src/app/ui/buttons/Kakao.tsx
  src/app/ui/buttons/SignOut.tsx
  src/app/ui/common/Header.tsx
  src/app/ui/common/Input.tsx
  src/app/ui/common/Modal.tsx
  src/app/ui/common/Navbar.tsx
  src/app/ui/common/Textarea.tsx
  src/app/ui/common/Title.tsx
  src/app/ui/fonts.ts
  src/app/write/_components/PhotoBooth.tsx
  src/app/write/page.tsx
  src/constants/signup/index.ts
  src/validator/index.js
  src/validator/is-valid-birth/index.js
  src/validator/is-valid-birth/index.test.js
Labels: ✨ Feature, 📱 FE, ⚙️Settings, 🎨 Html&css

#44 Feat: map 퍼블리싱을 완료한다.
  assets/icons/map/bottom-arrow.svg
  assets/icons/map/facebook.svg
  assets/icons/map/glass.svg
  assets/icons/map/homepage.svg
  assets/icons/map/index.ts
  assets/icons/map/insignia.svg
  assets/icons/map/insta.svg
  assets/icons/map/map.svg
  assets/icons/map/marker.svg
  assets/icons/map/phone.svg
  env.d.ts
  next.config.js
  package-lock.json
  package.json
  postcss.config.js
  src/__mock__/data/map.mock.ts
  src/__mock__/handler/server/index.ts
  src/__mock__/handler/server/map.ts
  src/app/_components/ui/button.tsx
  src/app/_components/ui/carousel.tsx
  src/app/layout.tsx
  src/app/service/community/_components/User.tsx
  src/app/service/layout.tsx
  src/app/service/map/_components/Review/ReviewModal.tsx
  src/app/service/map/_components/map/BarRatingChart.tsx
  src/app/service/map/_components/map/BottomSheetContainer.tsx
  src/app/service/map/_components/map/BottomSheetInner.tsx
  src/app/service/map/_components/map/KakaoBackGroundMap.tsx
  src/app/service/map/_components/map/LineRatingChart.tsx
  src/app/service/map/_components/map/OneSearchResult.tsx
  src/app/service/map/_components/map/OneSiteUrl.tsx
  src/app/service/map/_components/map/SearchBar.tsx
  src/app/service/map/_components/map/SearchResultModal.tsx
  src/app/service/map/page.tsx
  src/app/styles/globals.css
  src/app/ui/common/ImageCarousel.tsx
  src/app/ui/common/Ratingbar.tsx
  src/app/ui/fonts.ts
  src/app/ui/modal/ImageModal.tsx
  src/app/ui/modal/ImageSliderModal.tsx
  src/constants/map/index.ts
  src/hooks/common/useCss.ts
  src/hooks/map/useMap.ts
  src/styles/globals.css
  src/types/map/BottomSheetProps.ts
  src/types/map/ReviewProps.ts
  src/types/map/map.ts
  src/types/ui/common/ImageCarousel.ts
  src/types/ui/modal/ImageModal.ts
  src/types/ui/modal/ImageSliderModal.ts
  src/util/getAvgPoint.ts
  src/util/getTimeDiff.ts
  tailwind.config.ts
  tsconfig.json
Labels: ✨ Feature, 📱 FE, 🎨 Html&css

#46 Design: map의 스타일과 폴더 구조를 변경한다.
  .eslintignore
  .eslintrc.json
  assets/icons/map/bottom-arrow.svg
  assets/icons/map/facebook.svg
  assets/icons/map/glass.svg
  assets/icons/map/homepage.svg
  assets/icons/map/index.ts
  assets/icons/map/insignia.svg
  assets/icons/map/insta.svg
  assets/icons/map/map.svg
  assets/icons/map/marker.svg
  assets/icons/map/phone.svg
  src/__mock__/data/map.mock.ts
  src/app/_components/buttons/Button.tsx
  src/app/_components/buttons/Floating.tsx
  src/app/_components/buttons/Kakao.tsx
  src/app/_components/buttons/SignOut.tsx
  src/app/_components/common/Header.tsx
  src/app/_components/common/ImageCarousel.tsx
  src/app/_components/common/Input.tsx
  src/app/_components/common/Modal.tsx
  src/app/_components/common/Navbar.tsx
  src/app/_components/common/Ratingbar.tsx
  src/app/_components/common/Textarea.tsx
  src/app/_components/common/Title.tsx
  src/app/_components/modal/ImageModal.tsx
  src/app/_components/modal/ImageSliderModal.tsx
  src/app/_components/ui/button.tsx
  src/app/_components/ui/carousel.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/service/_components/NavigateBlock.tsx
  src/app/service/_components/Notice.tsx
  src/app/service/community/_components/comment/CommentButtons.tsx
  src/app/service/community/layout.tsx
  src/app/service/community/page.tsx
  src/app/service/layout.tsx
  src/app/service/map/_components/Review/ReviewModal.tsx
  src/app/service/map/_components/map/BarRatingChart.tsx
  src/app/service/map/_components/map/BottomSheetContainer.tsx
  src/app/service/map/_components/map/BottomSheetInner.tsx
  src/app/service/map/_components/map/LineRatingChart.tsx
  src/app/service/map/_components/map/OneSearchResult.tsx
  src/app/service/map/_components/map/OneSiteUrl.tsx
  src/app/service/map/_components/map/SearchBar.tsx
  src/app/service/map/_components/map/SearchResultModal.tsx
  src/app/service/map/page.tsx
  src/app/service/my-page/_components/Profile.tsx
  src/app/service/my-page/_components/Withdrawal.tsx
  src/app/service/my-page/page.tsx
  src/app/service/page.tsx
  src/app/sign-up/_components/SignUpForm.tsx
  src/app/write/page.tsx
  src/hooks/map/useMap.ts
  src/styles/color.ts
  src/styles/font/Giants-Regular.ttf
  src/styles/font/PretendardVariable.woff2
  src/styles/font/index.ts
  src/types/map/map.ts
Labels: 🔨 Refactor, 📱 FE, 🎨 Html&css

#47 Chore: msw를 추가한다.
  .env.sample
  .eslintignore
  .gitignore
  env.d.ts
  next.config.js
  package.json
  public/mockServiceWorker.js
  src/__mock__/browser.ts
  src/__mock__/handler/client/community.ts
  src/__mock__/handler/client/index.ts
  src/__mock__/handler/server/index.ts
  src/app/layout.tsx
  src/app/providers.tsx
  src/constants/api/index.ts
  src/lib/axios/axios-instance.ts
  src/lib/msw/mock-enable.ts
Labels: 🔨 Refactor, 📱 FE, ⚙️Settings
