Repository Kernel360/f1-Orury-Client, pull requests merged in 2024-01, with the labels that each got.

#49 Design: #45 review 1차 구현 완료
  .eslintrc.json
  package-lock.json
  package.json
  src/__mock__/data/review.mock.ts
  src/app/_components/modal/ImageModal.tsx
  src/app/_components/modal/ImageSliderModal.tsx
  src/app/service/map/_components/MapCarousel.tsx
  src/app/service/map/_components/Review/FirstReviewModal.tsx
  src/app/service/map/_components/Review/OneReview.tsx
  src/app/service/map/_components/Review/ReviewList.tsx
  src/app/service/map/_components/Review/ReviewModal.tsx
  src/app/service/map/_components/Review/SatisfiedRating.tsx
  src/app/service/map/_components/map/BottomSheetInner.tsx
  src/app/service/map/_components/map/OneSearchResult.tsx
  src/app/service/map/page.tsx
  src/types/map/BottomSheetProps.ts
  src/types/map/ReviewProps.ts
  src/types/map/review.ts
Labels: ✨ Feature, 📱 FE, 🎨 Html&css

#50 Design: 댓글 수정 UI 구현
  .eslintrc.json
  src/__mock__/data/comment.mock.ts
  src/__mock__/data/post.mock.ts
  src/__mock__/handler/server/community.ts
  src/app/_components/buttons/Button.tsx
  src/app/_components/common/Content.tsx
  src/app/_components/common/Header.tsx
  src/app/_components/common/Input.tsx
  src/app/_components/common/Modal.tsx
  src/app/_components/common/ModifyInput.tsx
  src/app/_components/common/TextInput.tsx
  src/app/_components/ui/MenuBar.tsx
  src/app/_components/ui/textarea.tsx
  src/app/page.tsx
  src/app/service/community/[id]/_components/PostDetail.tsx
  src/app/service/community/[id]/api/getPostDetail.ts
  src/app/service/community/[id]/api/postDetail.d.ts
  src/app/service/community/[id]/page.tsx
  src/app/service/community/_components/Post.tsx
  src/app/service/community/_components/Posts.tsx
  src/app/service/community/_components/SearchBar.tsx
  src/app/service/community/_components/Tabs.tsx
  src/app/service/community/_components/User.tsx
  src/app/service/community/_components/comment/Comment.tsx
  src/app/service/community/_components/comment/CommentBar.tsx
  src/app/service/community/_components/comment/CommentButtons.tsx
  src/app/service/community/_components/comment/Content.tsx
  src/app/service/community/api/getPosts.ts
  src/app/service/community/api/route.ts
  src/app/service/community/hot/page.tsx
  src/app/service/community/layout.tsx
  src/app/service/community/page.tsx
  src/app/service/community/qna/page.tsx
  src/app/service/my-page/_components/Profile.tsx
  src/app/sign-up/_components/SignUpForm.tsx
  src/app/write/_components/PhotoBooth.tsx
  src/app/write/_components/PhotoBoothButton.tsx
  src/app/write/page.tsx
  src/constants/api/end-point.ts
  src/constants/community/tabs.ts
  src/constants/ui/common/modal.ts
  src/middleware.ts
  src/store/community/commentStore.ts
  src/store/community/postsStore.ts
  src/styles/globals.css
  src/types/common/modifyInput.ts
  src/types/community/comment.ts
  src/types/community/commentButtons.ts
  src/types/community/posts.ts
  src/types/community/user.ts
  src/types/ui/common/contentArea.ts
  src/types/ui/common/input.ts
  src/types/ui/common/textarea.ts
  tailwind.config.ts
  tsconfig.json
Labels: 📱 FE, 🎨 Html&css

#52 Design/#45 review 2차 구현 완료
  .eslintrc.json
  next.config.js
  package-lock.json
  package.json
  src/__mock__/data/map.mock.ts
  src/__mock__/data/review.mock.ts
  src/__mock__/handler/client/community.ts
  src/app/_components/ui/dropdown-menu.tsx
  src/app/providers.tsx
  src/app/service/map/_components/Review/IconChipList.tsx
  src/app/service/map/_components/Review/IconContainer.tsx
  src/app/service/map/_components/Review/OneReview.tsx
  src/app/service/map/_components/Review/ReviewList.tsx
  src/app/service/map/_components/Review/ReviewModal.tsx
  src/app/service/map/_components/Review/ReviewRegisterModal.tsx
  src/app/service/map/_components/Review/SatisfiedRating.tsx
  src/app/service/map/_components/map/BottomSheetContainer.tsx
  src/app/service/map/_components/map/KakaoBackGroundMap.tsx
  src/app/service/map/page.tsx
  src/lib/msw/mock-enable.ts
  src/store/review/reviewStore.ts
  src/types/map/ReviewProps.ts
  src/types/map/review.ts
Labels: ✨ Feature, 🐞 Fix, 🔨 Refactor, 📱 FE, 🎨 Html&css

#62 feat : 클라이언트 ec2 자동배포 테스트
  .github/workflows/deploy.yml
  appspec.yml
  deploy.sh
Labels: 🌏 Deploy, ⚙️Settings

#63 fix : 자동 배포 로직 수정
  .github/workflows/deploy.yml
  deploy.sh
  package.json
Labels: 💻 BE

#64 fix : env-cmd 의존성 추가
  package.json
Labels: 🌏 Deploy, ⚙️Settings

#61 docs: #60 README 2차 작성
  README.md
Labels: 📃 Docs, 📱 FE

#58 Refactor: #51 로그인 구현 이전 임시 토큰을 통한 API 통신 구현
  env.d.ts
  next.config.js
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/app/_components/common/Form.tsx
  src/app/_components/ui/carousel.tsx
  src/app/page.tsx
  src/app/providers.tsx
  src/app/service/community/[id]/api/editComment.ts
  src/app/service/community/[id]/api/postComment.ts
  src/app/service/community/_components/PostList.tsx
  src/app/service/community/_components/PostListSkeleton.tsx
  src/app/service/community/api/editPost.ts
  src/app/service/community/api/post.ts
  src/constants/api/end-point.ts
  src/hooks/community/usePostListInfinite.ts
  src/lib/axios/axios-instance.ts
  src/lib/cookie.ts
  src/types/common/cookie.ts
  src/utils/crypto.ts
  src/utils/fetcher.ts
  src/utils/getKeys.ts
Labels: ✨ Feature, 📱 FE, ⚙️Settings

#66 Refactor: #51 kakao 소셜 로그인 구현 및 리팩토링 완료
  src/app/_components/buttons/Kakao.tsx
  src/app/api/auth/getUserInfo.ts
  src/app/page.tsx
  src/app/sign-in/kakao/page.tsx
  src/constants/api/end-point.ts
  src/constants/api/statusCode.ts
  src/constants/url.ts
  src/lib/axios/axios-instance.ts
  src/store/sign-in/signInStore.ts
  src/store/sign-up/signUpStore.ts
  src/types/sign-in/index.ts
  src/types/sign-up/index.ts
  src/utils/fetcher.ts
Labels: ✨ Feature, 📱 FE

#68 Feat: #67 PWA 기능 세팅 완료
  next.config.js
  package-lock.json
  package.json
  public/favicon.ico
  public/favicons/apple-icon.png
  public/favicons/favicon-16x16.png
  public/favicons/favicon-32x32.png
  public/icons/icon-128x128.png
  public/icons/icon-144x144.png
  public/icons/icon-152x152.png
  public/icons/icon-192x192.png
  public/icons/icon-256x256.png
  public/icons/icon-384x384.png
  public/icons/icon-48x48.png
  public/icons/icon-512x512.png
  public/icons/icon-72x72.png
  public/icons/icon-96x96.png
  public/manifest.json
  src/app/layout.tsx
Labels: ✨ Feature, 📱 FE
