Repository Kernel360/f1-Orury-Client, pull requests merged in 2024-05, with the labels that each got.

#134 Design: #128 커뮤니티 리디자인
  assets/images/searching.png
  src/app/_components/common/Ellipsis.tsx
  src/app/_components/common/Header.tsx
  src/app/_components/common/Modal.tsx
  src/app/_components/common/Navbar.tsx
  src/app/_components/common/Tabs.tsx
  src/app/_components/ui/accordion.tsx
  src/app/_components/ui/menubars.tsx
  src/app/_components/ui/textarea.tsx
  src/app/service/_components/Notice.tsx
  src/app/service/community/[id]/_components/PostDetail.tsx
  src/app/service/community/[id]/_components/comment/CommentButtons.tsx
  src/app/service/community/[id]/_components/comment/CommentInput.tsx
  src/app/service/community/[id]/_components/comment/CommentList.tsx
  src/app/service/community/[id]/_components/comment/Content.tsx
  src/app/service/community/[id]/_components/comment/OneComment.tsx
  src/app/service/community/[id]/api/deleteCommentLike.ts
  src/app/service/community/[id]/api/postCommentLike.ts
  src/app/service/community/[id]/page.tsx
  src/app/service/community/_components/Category.tsx
  src/app/service/community/_components/CommunityModal.tsx
  src/app/service/community/_components/NotSearched.tsx
  src/app/service/community/_components/OnePost.tsx
  src/app/service/community/_components/PhotoBooth.tsx
  src/app/service/community/_components/PostForm.tsx
  src/app/service/community/_components/PostList.tsx
  src/app/service/community/_components/SearchBar.tsx
  src/app/service/community/_components/User.tsx
  src/app/service/community/page.tsx
  src/app/service/page.tsx
  src/app/service/user/_components/Withdrawal.tsx
  src/app/service/user/page.tsx
  src/app/sign-in/apple/page.tsx
  src/app/sign-in/kakao/page.tsx
  src/constants/community/tabs.ts
  src/constants/ui/common/modal.ts
  src/constants/ui/common/navbar.ts
  src/constants/url.ts
  src/hooks/community/useCommentList.ts
  src/styles/color.ts
  src/styles/globals.css
  src/types/common/form.ts
  src/types/community/comment.ts
  src/types/community/commentButtons.ts
  src/types/community/post.ts
  src/types/community/searchBar.ts
  src/types/community/user.ts
  src/types/ui/common/ellipsis.ts
  src/types/ui/common/header.ts
  src/utils/convertURLtoFile.ts
  src/utils/getKeys.ts
  tailwind.config.ts
Labels: 📱 FE, 🎨 Html&css

#137 Feat: #136 회원가입 (온보딩) 리팩토링
  assets/images/loadingLogo.png
  src/app/_components/buttons/Button.tsx
  src/app/_components/common/Header.tsx
  src/app/_components/common/Tabs.tsx
  src/app/_components/common/UserProfileImage.tsx
  src/app/service/community/_components/PostForm.tsx
  src/app/sign-in/kakao/page.tsx
  src/app/sign-up/_components/Banner.tsx
  src/app/sign-up/_components/ProgressBar.tsx
  src/app/sign-up/_components/SignUpForm.tsx
  src/app/sign-up/_components/Step1/index.tsx
  src/app/sign-up/_components/Step2/Check.tsx
  src/app/sign-up/_components/Step2/RequiredStar.tsx
  src/app/sign-up/_components/Step2/SignUpForm.tsx
  src/app/sign-up/_components/Step2/TosModal.tsx
  src/app/sign-up/_components/Step2/TosSummary.tsx
  src/app/sign-up/_components/Step2/index.tsx
  src/app/sign-up/_components/Step3/index.tsx
  src/app/sign-up/api/postSignUp.ts
  src/app/sign-up/page.tsx
  src/app/sign-up/schema.ts
  src/constants/sign-up/index.ts
  src/constants/utils/getFormData.ts
  src/store/user/userStore.ts
  src/types/common/profileImage.ts
  src/types/sign-in/index.ts
  src/types/sign-up/index.ts
  src/types/ui/common/header.ts
  src/utils/getFormData.ts
  tailwind.config.ts
Labels: ✨ Feature, 🔨 Refactor, 📱 FE, 🎨 Html&css

#139 Feat: #138 map write
  src/app/service/map/_components/bottom-sheet/BottomSheetHeader.tsx
  src/app/service/map/_components/bottom-sheet/BottomSheetReviewTab.tsx
  src/app/service/map/_components/bottom-sheet/WriteModal.tsx
  src/types/review/review.ts
Labels: ✨ Feature, 📱 FE, 🎨 Html&css

#143 Fix/#142 fix reaction
  src/app/_components/review/review-component/IconChipList.tsx
  src/app/_components/review/review-component/SatisfiedRating.tsx
  src/app/_components/review/review-modal/OneReview.tsx
  src/app/service/crew/[id]/_components/MemberList.tsx
  src/types/review/ReviewProps.ts
Labels: 🐞 Fix, 📱 FE
