Repository Kernel360/f1-Orury-Client, pull requests merged in 2024-02, with the labels that each got.

#72 fix : 프론트 자동배포 처리
  .github/workflows/deploy.yml
  appspec.yml
  deploy.sh
Labels: 🌏 Deploy, ⚙️Settings

#73 Fix/#71 auto deploy
  .github/workflows/deploy.yml
Labels: 🌏 Deploy, ⚙️Settings

#74 fix: #65 회원가입 후 토큰 및 쿠키 관리 오류 수정
  src/app/sign-in/kakao/page.tsx
  src/app/sign-up/_components/SignUpForm.tsx
  src/app/sign-up/api/postSignUp.ts
  src/types/my-page/index.ts
  src/types/sign-up/index.ts
  src/utils/setTokensInCookies.ts
Labels: 🐞 Fix, 📱 FE

#76 Feat: #42 중간 배포 이전 커뮤니티 기능 구현
  .eslintrc.json
  .husky/pre-commit
  .prettierignore
  src/app/_components/common/Form.tsx
  src/app/_components/common/Header.tsx
  src/app/_components/modal/ImageSliderModal.tsx
  src/app/_components/ui/dropdown-menu.tsx
  src/app/_components/ui/toast.tsx
  src/app/_components/ui/use-toast.ts
  src/app/schema.ts
  src/app/service/community/[id]/_components/PostDetail.tsx
  src/app/service/community/[id]/_components/comment/CommentButtons.tsx
  src/app/service/community/[id]/_components/comment/CommentInput.tsx
  src/app/service/community/[id]/_components/comment/OneComment.tsx
  src/app/service/community/[id]/api/deleteComment.ts
  src/app/service/community/[id]/api/deleteCommentLike.ts
  src/app/service/community/[id]/api/deletePost.ts
  src/app/service/community/[id]/api/deletePostLike.ts
  src/app/service/community/[id]/api/editComment.ts
  src/app/service/community/[id]/api/getPostDetail.ts
  src/app/service/community/[id]/api/postComment.ts
  src/app/service/community/[id]/api/postCommentLike.ts
  src/app/service/community/[id]/api/postPostLike.ts
  src/app/service/community/[id]/api/route.ts
  src/app/service/community/[id]/page.tsx
  src/app/service/community/_components/CountItem.tsx
  src/app/service/community/_components/Counts.tsx
  src/app/service/community/_components/OnePost.tsx
  src/app/service/community/_components/PhotoBooth.tsx
  src/app/service/community/_components/SearchBar.tsx
  src/app/service/community/_components/SearchPostSection.tsx
  src/app/service/community/_components/User.tsx
  src/app/service/community/api/editPost.ts
  src/app/service/community/api/post.ts
  src/constants/api/end-point.ts
  src/constants/common/form.ts
  src/constants/utils/getFormData.ts
  src/hooks/community/useSearchPostListInfinite.ts
  src/middleware.ts
  src/store/community/postsStore.ts
  src/styles/color.ts
  src/types/community/counts.ts
  src/types/community/photoBooth.ts
  src/types/community/post.ts
  src/utils/getKeys.ts
Labels: ✨ Feature, 📱 FE

#79 Fix: #56 review UI, 버그 수정
  src/app/_components/modal/ImageModal.tsx
  src/app/_components/review/review-modal/ReviewModal.tsx
  src/app/_components/review/review-modal/ReviewModalContainer.tsx
  src/app/_components/review/review-modal/ReviewRegisterModal.tsx
  src/app/service/map/_components/bottom-sheet/BottomSheetInner.tsx
Labels: 🐞 Fix, 📱 FE

#80 Feat: 중간 발표용 고객의 소리함 추가
  src/app/service/_components/Notice.tsx
Labels: ✨ Feature, 📱 FE

#81 Fix: 카카오 로그인 리다이렉션 오류 수정
  src/app/service/community/_components/PhotoBooth.tsx
  src/app/sign-in/kakao/page.tsx
Labels: ✨ Feature, 🐞 Fix, 📱 FE

#82 HOTFIX: hydration error 임시 수정
  src/app/service/community/_components/PhotoBooth.tsx
Labels: ❗ Bug, 🐞 Fix

#87 Fix: #84 중간 배포 이후 버그 수정
  README.md
  package-lock.json
  package.json
  src/apis/auth/getNewAccessToken.ts
  src/apis/auth/getNewToken.ts
  src/app/_components/common/Form.tsx
  src/app/_components/common/Header.tsx
  src/app/_components/common/ModifyInput.tsx
  src/app/_components/common/TextInput.tsx
  src/app/_components/ui/radio-group.tsx
  src/app/_components/ui/use-toast.ts
  src/app/page.tsx
  src/app/schema.ts
  src/app/service/community/[id]/_components/EditPostDetail.tsx
  src/app/service/community/[id]/_components/PostDetail.tsx
  src/app/service/community/[id]/_components/comment/CommentButtons.tsx
  src/app/service/community/[id]/_components/comment/CommentInput.tsx
  src/app/service/community/[id]/_components/comment/CommentList.tsx
  src/app/service/community/[id]/_components/comment/ModifyContent.tsx
  src/app/service/community/[id]/_components/comment/OneComment.tsx
  src/app/service/community/[id]/schema.ts
  src/app/service/community/_components/CommunityModal.tsx
  src/app/service/community/_components/CountItem.tsx
  src/app/service/community/_components/OnePost.tsx
  src/app/service/community/_components/PhotoBooth.tsx
  src/app/service/community/_components/PostList.tsx
  src/app/service/community/_components/PostListSkeleton.tsx
  src/app/service/community/api/editPost.ts
  src/app/service/user/_components/Activity.tsx
  src/app/service/user/_components/Profile.tsx
  src/app/service/user/page.tsx
  src/app/sign-in/kakao/page.tsx
  src/app/sign-up/_components/SignUpForm.tsx
  src/app/sign-up/_components/TosModal.tsx
  src/app/sign-up/_components/TosSummary.tsx
  src/app/sign-up/page.tsx
  src/app/sign-up/schema.ts
  src/constants/api/statusCode.ts
  src/constants/common/form.ts
  src/constants/community/comment.ts
  src/constants/sign-in/index.ts
  src/constants/sign-up/index.ts
  src/constants/url.ts
  src/hooks/community/useCommentList.ts
  src/hooks/community/useCommentListInfinite.ts
  src/hooks/community/usePostList.ts
  src/hooks/community/usePostListInfinite.ts
  src/hooks/community/useSearchPostListInfinite.ts
  src/hooks/user/useUserPostListInfinite.ts
  src/lib/axios/axios-instance.ts
  src/lib/axios/interceptor.ts
  src/store/user/userStore.ts
  src/types/community/post.ts
  src/types/sign-in/index.ts
  src/types/sign-up/index.ts
  src/utils/autoResize.ts
  src/utils/fetcher.ts
  src/utils/getKeys.ts
Labels: ✨ Feature, 🐞 Fix, 📱 FE
