Repository Kernel360/f1-Orury-Client, pull requests merged in 2024-03, with the labels that each got.

#91 Fix: review 버그 수정완료
  src/apis/review/apis/review.ts
  src/app/_components/review/review-modal/ReviewModal.tsx
  src/app/service/map/page.tsx
  src/constants/api/end-point.ts
Labels: 🐞 Fix, 📱 FE

#95 Fix: #94 회원가입 중 생년월일 입력 폼 수정
  package-lock.json
  package.json
  src/app/_components/buttons/Apple.tsx
  src/app/page.tsx
  src/app/sign-in/kakao/page.tsx
  src/app/sign-up/_components/SignUpForm.tsx
  src/app/sign-up/schema.ts
  src/hooks/auth/useAppleAuth.ts
  src/store/user/userStore.ts
  src/types/sign-in/index.ts
  src/types/sign-up/index.ts
  src/utils/getEmail.ts
  tailwind.config.ts
Labels: 🐞 Fix, 🔨 Refactor, 📱 FE

#101 Feat/#90 (내 리뷰 목록 조회 api 응답에 맞는) review.ts interface 생성
  src/apis/review/hooks/useReview.ts
  src/app/_components/review/review-modal/MyReviewModal.tsx
  src/types/review/review.ts
Labels: 📬 API

#104 Fix: #92 리뷰 작성이 중지되는 현상 수정
  src/app/_components/review/review-modal/ReviewRegisterModal.tsx
  src/app/service/map/_components/search/SearchBar.tsx
  src/app/service/map/page.tsx
  src/types/review/review.ts
Labels: 🐞 Fix, 🔨 Refactor, 📱 FE

#107 Fix: #90 마이페이지 리뷰 조회시 나오지 않는 현상
  src/app/_components/review/review-modal/MyReviewModal.tsx
  src/app/_components/review/review-modal/ReviewRegisterModal.tsx
Labels: ❗ Bug, 🐞 Fix, 📱 FE

#112 Fix: #84 커뮤니티 게시글 이미지 로직 변경
  src/app/_components/common/Form.tsx
  src/app/_components/review/review-modal/MyReviewModal.tsx
  src/app/_components/review/review-modal/ReviewModalContainer.tsx
  src/app/service/_components/Notice.tsx
  src/app/service/community/[id]/page.tsx
  src/app/service/community/api/editPost.ts
  src/app/service/user/_components/Profile.tsx
  src/app/service/user/page.tsx
  src/store/community/postsStore.ts
  src/types/common/form.ts
  src/types/community/post.ts
Labels: 🐞 Fix, 📱 FE

#114 design: public icon 변경
  public/icons/icon-128x128.jpg
  public/icons/icon-128x128.png
  public/icons/icon-144x144.jpg
  public/icons/icon-144x144.png
  public/icons/icon-152x152.jpg
  public/icons/icon-152x152.png
  public/icons/icon-192x192.jpg
  public/icons/icon-192x192.png
  public/icons/icon-256x256.jpg
  public/icons/icon-256x256.png
  public/icons/icon-384x384.jpg
  public/icons/icon-384x384.png
  public/icons/icon-48x48.jpg
  public/icons/icon-48x48.png
  public/icons/icon-512x512.jpg
  public/icons/icon-512x512.png
  public/icons/icon-72x72.jpg
  public/icons/icon-72x72.png
  public/icons/icon-96x96.jpg
  public/icons/icon-96x96.png
Labels: 📱 FE, ⚙️Settings

#118 fix: jpg -> white background png로 수정
  public/icons/icon-1024x1024.jpg
  public/icons/icon-1024x1024.png
  public/icons/icon-128x128.jpg
  public/icons/icon-128x128.png
  public/icons/icon-144x144.jpg
  public/icons/icon-144x144.png
  public/icons/icon-152x152.jpg
  public/icons/icon-152x152.png
  public/icons/icon-192x192.jpg
  public/icons/icon-192x192.png
  public/icons/icon-256x256.jpg
  public/icons/icon-256x256.png
  public/icons/icon-384x384.jpg
  public/icons/icon-384x384.png
  public/icons/icon-48x48.jpg
  public/icons/icon-48x48.png
  public/icons/icon-512x512.jpg
  public/icons/icon-512x512.png
  public/icons/icon-72x72.jpg
  public/icons/icon-72x72.png
  public/icons/icon-96x96.jpg
  public/icons/icon-96x96.png
  public/manifest.json
Labels: 📱 FE, ⚙️Settings

#122 Design: #121 알림 기능 UI 구현
  src/__mock__/data/alert.mock.ts
  src/app/_components/common/Header.tsx
  src/app/_components/common/Title.tsx
  src/app/_components/home/GuideModal.tsx
  src/app/alert/_components/Card.tsx
  src/app/alert/page.tsx
  src/app/page.tsx
  src/app/service/page.tsx
  src/constants/url.ts
  src/types/alert/index.ts
Labels: 📱 FE, 🎨 Html&css

#124 feat: 알림 내역 조회 기능 추가
  src/__mock__/data/alert.mock.ts
  src/app/alert/_components/Card.tsx
  src/app/alert/page.tsx
  src/app/notification/_components/Card.tsx
  src/app/notification/page.tsx
  src/app/service/community/_components/User.tsx
  src/app/service/page.tsx
  src/constants/api/end-point.ts
  src/constants/url.ts
  src/hooks/notification/useNotificationList.ts
  src/lib/axios/interceptor.ts
  src/types/alert/index.ts
  src/types/common/response.ts
  src/types/notification/index.ts
  src/utils/getKeys.ts
Labels: ✨ Feature, 📱 FE
